export const SKILLS = [
  "React.js",
  "Node.js",
  "MongoDB",
  "Typescript",
  "JavaScript",
  "HTML",
  "CSS",
  "Next.js",
  "Tailwind",
  "Figma",
  "Microsoft SQL Server",
  "PostgreSQL",
  "Express.js",
  "Nest.js",
  "Serverless Functions",
  "Microsoft Azure Services",
  "Microsoft Azure Storage Account",
  "Azure Active Directory",
  "CI/CD",
  "Docker",
  "IaC",
  "Microservices",
];
